slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # Frames & Topics
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    mode: mapping

    # Debug
    debug_logging: false

    # Timing / Publishing
    throttle_scans: 1
    transform_publish_period: 0.02   # 50 Hz
    map_update_interval: 5.0
    minimum_time_interval: 0.1
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    restamp_tf: false

    # Map
    resolution: 0.05
    stack_size_to_use: 40000000
    enable_interactive_mode: true
    occupancy_threshold: 0.1

    # Laser
    min_laser_range: 0.0
    max_laser_range: 16.0

    # Motion filter (중요 ↓)
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
    check_min_dist_and_heading_precisely: false

    # Scan buffer
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 14.0

    # Scan matching
    use_scan_matching: true
    use_scan_barycenter: true
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5

    # Loop closure
    do_loop_closing: true
    loop_search_maximum_distance: 2.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation (local)
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation (loop)
    loop_search_space_dimension: 6.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher penalties
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    minimum_distance_penalty: 0.5
    minimum_angle_penalty: 0.9

    # Search angles
    fine_search_angle_offset: 0.00349     # ~0.2 deg
    coarse_search_angle_offset: 0.349     # ~20 deg
    coarse_angle_resolution: 0.0349       # ~2 deg

    # Misc
    use_response_expansion: true
    m

